// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDApkZ764uS7E1xEt4jdq7_FRsTtVtTo',
    appId: '1:1093954681964:web:50387ea7aac912f8eeac49',
    messagingSenderId: '1093954681964',
    projectId: 'crudfirebase-61204',
    authDomain: 'crudfirebase-61204.firebaseapp.com',
    storageBucket: 'crudfirebase-61204.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGMqutRHPcRzjyftHACHJjk7kJy5urng',
    appId: '1:1093954681964:android:8a2216e29b42da2deeac49',
    messagingSenderId: '1093954681964',
    projectId: 'crudfirebase-61204',
    storageBucket: 'crudfirebase-61204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5g7rofXAFuodb_oP34vtmaDBP_4NEVM',
    appId: '1:1093954681964:ios:aa2e15cff040125beeac49',
    messagingSenderId: '1093954681964',
    projectId: 'crudfirebase-61204',
    storageBucket: 'crudfirebase-61204.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5g7rofXAFuodb_oP34vtmaDBP_4NEVM',
    appId: '1:1093954681964:ios:aa2e15cff040125beeac49',
    messagingSenderId: '1093954681964',
    projectId: 'crudfirebase-61204',
    storageBucket: 'crudfirebase-61204.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnDApkZ764uS7E1xEt4jdq7_FRsTtVtTo',
    appId: '1:1093954681964:web:adea74bba5bd454ceeac49',
    messagingSenderId: '1093954681964',
    projectId: 'crudfirebase-61204',
    authDomain: 'crudfirebase-61204.firebaseapp.com',
    storageBucket: 'crudfirebase-61204.firebasestorage.app',
  );
}
